name: workflow using Snyk with continue on error
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: cd SCA/JS; npm install
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        with:
         command: monitor
         args: --org=prod-team
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
