name: Notify PR Author on Status Check Failure

on:
  status:
    types: [failure]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Check if PR is related to status
      id: pr_info
      run: |
        # Check if the status context is related to a PR commit
        COMMIT_SHA=${{ github.sha }}
        PR_NUMBER=$(curl -s "https://api.github.com/repos/${{ github.repository }}/commits/$COMMIT_SHA/pull" | jq -r '.[0].number')
        echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
        echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV

    - name: Post comment on PR
      if: ${{ env.PR_NUMBER != 'null' }}
      uses: actions/github-script@v6
      with:
        script: |
          const { context, github } = require('@actions/github');
          const prNumber = process.env.PR_NUMBER;
          const repo = context.repo.repo;
          const owner = context.repo.owner;
          const message = '🚨 One of the required status checks has failed. Please address the issue before proceeding with the PR.';

          // Post comment on the PR
          await github.issues.createComment({
            owner,
            repo,
            issue_number: prNumber,
            body: message
          });

    - name: Notify if PR number could not be found
      if: ${{ env.PR_NUMBER == 'null' }}
      run: echo "No associated PR found for the failed status check."
