name: Notify PR Author on Status Check Failure

on:
  status:
    types: [failure]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Get pull request details from the status context
    - name: Get PR Details
      id: pr_details
      run: |
        echo "Fetching pull request details..."
        PR_URL=$(curl -s "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}" | jq -r .commit.tree.url)
        PR_NUMBER=$(curl -s "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}" | jq -r .commit.message)
        echo "PR_URL=${PR_URL}" >> $GITHUB_ENV
        echo "PR_NUMBER=${PR_NUMBER}" >> $GITHUB_ENV

      # Step 2: Post a comment on the PR
    - name: Post Comment on PR
      uses: actions/github-script@v6
      with:
        script: |
          const { context, github } = require('@actions/github');
          const issue_number = context.payload.pull_request.number;
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          const message = '🚨 One of the required status checks has failed. Please address the issue before proceeding with the PR.';

          await github.issues.createComment({
            owner,
            repo,
            issue_number,
            body: message
          });
