name: Notify PR Author on Status Check Failure

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Get PR author details
        id: pr_details
        run: |
          # Get the PR author's GitHub username
          PR_AUTHOR=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | jq -r .user.login)
          echo "PR Author: $PR_AUTHOR"
          echo "PR_AUTHOR=$PR_AUTHOR" >> $GITHUB_ENV

      - name: Get PR status checks
        id: pr_status
        run: |
          # Fetch the check runs for the PR
          PR_CHECKS=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/check-runs")

          # Check if the response is null or contains no check runs
          if [[ "$PR_CHECKS" == "null" || "$PR_CHECKS" == "[]" ]]; then
            echo "No check runs found for this PR."
            echo "FAILURE_FOUND=0" >> $GITHUB_ENV
            exit 0
          fi

          # Extract the conclusion of each check run
          echo "$PR_CHECKS" | jq -r '.check_runs[].conclusion' > conclusions.txt

          # Check if any status check is a failure
          FAILURE_FOUND=$(grep -c "failure" conclusions.txt)
          echo "Failures found: $FAILURE_FOUND"
          echo "FAILURE_FOUND=$FAILURE_FOUND" >> $GITHUB_ENV

      - name: Post a comment on the PR if status check failed
        if: ${{ env.FAILURE_FOUND > 0 }}
        run: |
          echo "Posting a comment on the PR..."

          # Post a comment on the PR notifying the author
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
                  "body": "Hello @'$PR_AUTHOR',\n\nThe required status check for your PR (#${{ github.event.pull_request.number }}) has failed. Please check the status checks on GitHub for more details.\n\nBest regards,\nGitHub CI/CD"
                }' \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"

      - name: No status check failure
        if: ${{ env.FAILURE_FOUND == 0 }}
        run: |
          echo "Status Check Passed"
