name: Notify on Status Check Failure

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Check status of PR
        run: |
          PR_STATUS=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/checks")

          if [[ $PR_STATUS == *"status: failure"* ]]; then
            # Send an email, Slack message, or use any notification service here
            echo "Status Check Failed"
          else
            echo "Status Check Passed"
          fi
