name: Prebuilt repo + Snyk Security Scanning (OS, Code, Docker, IaC)

# Runs 4 Snyk Products (Code, Open Source, Container, IaC)
# Snyk installation via npm
# Node.js version: 18.4
# Outputs the results to the pipeline and in SARIF-format to the security tab

# Prerequisites:
# - Set a SNYK_TOKEN and a SNYK_ORG in the pipelines secrets

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: cd SCA/JS; npm install

      - name: Use Node.js for installing Snyk
        uses: actions/setup-node@v2
        with:
          node-version: 18.4

      # Install & prepare Snyk
      - run: npm install --location=global snyk

      #  This OPTIONAL step will configure the Snyk CLI to connect to the EU instance of Snyk
      #- run: snyk config set endpoint='https://app.eu.snyk.io/api'

      - name: Setup Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth "$SNYK_TOKEN"

      - name: Snyk Open Source Scanning
        run: snyk test --org=${{ secrets.SNYK_ORG }} --all-projects --sarif-file-output=snyk-oss.sarif
        continue-on-error: true
      - name: Upload results to GitHub Open Source Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-oss.sarif

  
